name: Trigger Custom Windows Build

on:
  workflow_dispatch:

jobs:
  call-official-windows-build:
    uses: ./.github/workflows/build-windows.yml 
    with:
      platform: windows-x64
      runs-on: windows-2022
      debug-levels: '[ "release" ]'
      make-target: 'images' # 💥 强行指定只编译普通的 JDK 绿色镜像，不要带测试集
      msvc-toolset-version: '14.38' 
      msvc-toolset-architecture: '14.38.33130'
